### ISSUE TITLE
Update go-micro package to latest stable version.

### ISSUE THREAD

**Issue by bharath-b-hpe** [ODIM-Project/ODIM#112]
Update go-micro package used for RPCs between ODIM-RA services.

Update go-micro package to v1.18.0. And as consul used for service discovery in go-micro has been removed and etcd is used in the mentioned version, create docker image and manifest file for etcd(3.4.0).

- [x] Add docker image and manifest file
- [x] Update lib-utilities with go-micro v1.18.0
- [x] Update lib-utilities version in each source
- [x] Update CI/CD framework with the changes

go-micro version in the planned version(v1.18.0) is dependent on below two packages which doesn't have a license file in their project, hence this issue is re-opened to revert back the changes.
-	github.com/marten-seemann/chacha20
-	github.com/asim/protoc-gen-micro
In the master branch of go-micro, dependency on above two packages has been removed and will be updated when GA release of the same is made.

**Comment by rpieczon** [comment]
Why not latest stable 2.x?

**Comment by bharath-b-hpe** [comment]
Hi @rpieczon 

The reason for choosing go-micro v1.18.0 instead of latest v2 is because the v2 releases are happening very frequently. So we prefer something stable and avoid breaking functionality as some changes are non-backward compatible also. We will update to v2 and further releases in stages.

**Comment by rpieczon** [comment]
I see that also v3 is available (beta). Isn't that mean that we shouldn't expect any further changes in v2 branch?

**Comment by bharath-b-hpe** [comment]
Ideally yes. In this change we are updating go-micro from 1.13.0 to 1.18.0 and also changing the registry from consul to etcd. We will complete these changes and in the next enhancement we will update go-micro to v2 and make changes in a smooth and incremental manner.
