### ISSUE TITLE
Generation of GRPC API implementation should be automated.

### ISSUE THREAD

**Issue by rpieczon** [ODIM-Project/ODIM#114]
ODIM keeps autogenerated *.pb.go files under GIT management. Process is not automated and provided documentation doesn't describe how to regenerate existing files. 

I would suggest to make *.pb.go files generation part of build process (go generate would be helpful).
If for some reason you don't want to automate it, documentation describing manual generation process is a must.  

- [x] Adding script for downloading necessary tools and generating proto related files
- [ ] Automate the proto file generation by adding the script to the Docker/Make file

**Comment by ArturBaryla** [comment]
What's the status of that issue?

**Comment by a-ajith** [comment]
> hat's the status of that issue?

**Comment by Bharath-KKB** [comment]
> What's the status of that issue?

@ArturBaryla This change was on hold as we had issues building the stubs in the github build system. However this is no longer required as we are moving from go-micro to grpc.
