### ISSUE TITLE
improve implementation of create and update in persistence manager

### ISSUE THREAD

**Issue by Bharath-KKB** [ODIM-Project/ODIM#121]
Use NX/XX flags of redis while creating/updating data in DB to make these atomic. Do not use two statements to first check and then create/update.

**Comment by bharath-b-hpe** [comment]
Feature request and bugs are created and tracked from https://wiki.odim.io/. Hence closing this issue and https://jira.lfnetworking.org/browse/ODIM-27 is created to track the same.
