### ISSUE TITLE
Add support for X-Auth-Token in generic red fish plugin

### ISSUE THREAD

**Issue by Bharath-KKB** [ODIM-Project/ODIM#134]
The generic redfish plugin should hav support for both BasicAuth and X-Auth-Token for authenticating client requests.

**Comment by bharath-b-hpe** [comment]
Feature request and bugs are created and tracked from https://wiki.odim.io/. Hence closing this issue and https://jira.lfnetworking.org/browse/ODIM-28 is created to track the same.
