### ISSUE TITLE
ODIM is returning data with Content-Type as text/xml for /redfish/v1/$metadata and information under the same.

### ISSUE THREAD

**Issue by Bharath-KKB** [ODIM-Project/ODIM#212]
The Content type should be set as application/xml or application/xml;charset=utf-8 MIME types

**Comment by bharath-b-hpe** [comment]
Content-type in the response for /redfish/v1/$metadata request is updated to application/xml; charset=utf-8.

**Comment by bharath-b-hpe** [comment]
Feature request and bugs are created and tracked from https://wiki.odim.io/. Hence closing this issue and https://jira.lfnetworking.org/browse/ODIM-29 is created to track the same.
