### ISSUE TITLE
UnamangedRackPlugin:Incorrect response code returned while deleting a rackgroup which has rack attached to it

### ISSUE THREAD

**Issue by skhan-anjum** [ODIM-Project/ODIM#287]
Steps to reproduce:
1) Start URP Plugin
2) Add connection method for URP
3) Add URP in odimra
4) Create Rack Group
5) Create Rack with Rack Group created in step#4
6) Delete Rack Group without Deleting Rack
DELETE redfish/v1/Chassis/<chassis_id>
Expected Response Code : 406 
Actual Response Code: 404 not found

**Comment by Bharath-KKB** [comment]
Fixed elsewhere. It is returning 409.
