### ISSUE TITLE
URP: Attach Computer System chassis already patched to a rack to the same Rack again returns 200

### ISSUE THREAD

**Issue by skhan-anjum** [ODIM-Project/ODIM#293]
Steps to reproduce
1) Start URP service
2) Add BMC in odimra  
3) Add URP to odimra
4) Create Rack Group
5) Create Rack and do a patch operation on the uri returned in Location in response header as mentioned in 4th step
6) Attach Computer System chassis
PATCH redfish/v1/Chassis/b6766cb7-5721-5077-ae0e-3bf3683ad6e2
7) Attach Computer System chassis which is already attached in step6.
Expected Response :409
Actual response : 200

**Comment by rpieczon** [comment]
This is tricky. PATCH operation on a rack /redfish/v1/Chassis/{id} handles attach and detach activities. 

1. Attaching chassis under existing rack looks like:

```http
PATCH https://odimra.local.com:45000/redfish/v1/Chassis/Rack1

{
  "Links": {
    "Contains": [
      {
        "@odata.id": "/redfish/v1/Chassis/RackMount1"
      }
    ]
  }
}
```

2. Attaching another chassis under same existing rack looks like: 

```http
PATCH https://odimra.local.com:45000/redfish/v1/Chassis/Rack1

{
  "Links": {
    "Contains": [
      {
        "@odata.id": "/redfish/v1/Chassis/RackMount1"
      },
      {
        "@odata.id": "/redfish/v1/Chassis/RackMount2"
      }
    ]
  }
}
```

Note that already attached RackMount1 is specified again!

3. State of rack after these operation would be: 

```json


{
  ...
  "Links": {
    "ComputerSystems": [],
    "ManagedBy": [
      {
        "@odata.id": "/redfish/v1/Managers/99999999-9999-9999-9999-999999999999"
      }
    ],
    "Contains": [
      {
        "@odata.id": "/redfish/v1/Chassis/RackMount1"
      },
      {
        "@odata.id": "/redfish/v1/Chassis/RackMount2"
      }
    ],
    "ContainedBy": [
      {
        "@odata.id": "/redfish/v1/Chassis/RackGroup1"
      }
    ]
  }
  ...
}
```

4. Detaching RackMount2 would be: 

```http
PATCH https://odimra.local.com:45000/redfish/v1/Chassis/Rack1

{
  "Links": {
    "Contains": [
      {
        "@odata.id": "/redfish/v1/Chassis/RackMount1"
      }
    ]
  }
}
```

In step 4, you can see:
- request contains already attached RackMount1
- intention of this request is detach
- request is absolutely correct and cannot be rejected with proposed 409

In my opinion - not a bug.

**Comment by Bharath-KKB** [comment]
Yes this is not a bug.
