### ISSUE TITLE
URP : Attach a Computer System chassis already attached to a rack to a different Rack in the same Rack Group returns 400

### ISSUE THREAD

**Issue by skhan-anjum** [ODIM-Project/ODIM#294]
Steps to reproduce

1. Start URP service
2. Add BMC in odimra
3. Add URP to odimra
4. Create Rack Group RG#1
5. Create 2 Rack Rack#1 and Rack#2 in RG#1 and do a patch operation on the uri returned in Location in response header as mentioned in 4th step
6. Attach Computer System chassis to Rack#1
PATCH redfish/v1/Chassis/b6766cb7-5721-5077-ae0e-3bf3683ad6e2
7. Attach Computer System chassis which is already attached in step6. to Rack#2
Expected Response :409
Actual response : 400

**Comment by rpieczon** [comment]
Fixed.

**Comment by skhan-anjum** [comment]
Fixed. Returns 409 now
