### ISSUE TITLE
URP: get on computer system chassis (redfish/v1/chassis/<chassis_id>) in URP branch returns 500 internal server error

### ISSUE THREAD

**Issue by skhan-anjum** [ODIM-Project/ODIM#297]
Steps to Reproduce:
On Unamanged Rack Plugin branch ( This issue is not seen in upstream development):
1. Add GRF plugin
2. Add BMC with grf plugin
3. Do a get on the chassis that got added in step 2
GET redfish/v1/chassis/<chassis_id>
Expected Response : 200
Actual Response : 500 internal server error
{
"error": {
"code": "Base.1.6.1.GeneralError",
"message": "An error has occurred. See ExtendedInfo for more information.",
"@Message.ExtendedInfo": [
{
"@odata.type": "#Message.v1_0_8.Message",
"MessageId": "Base.1.6.1.InternalError",
"Message": "The request failed due to an internal service error. The service is still operational.json: cannot unmarshal string into Go struct field Chassis.IndicatorLED of type int",
"Severity": "Critical",
"Resolution": "Resubmit the request. If the problem persists, consider resetting the service."
}
]
}
}

**Comment by bobpiece** [comment]
Probably related with Chassis definition in lib-dmtf https://github.com/ODIM-Project/ODIM/blob/9cf1698bde15433402562835f732434c1cc165e4/lib-dmtf/model/Chassis.go#L37
