### ISSUE TITLE
UnmanagedRackPlugin : Unable to attach computer system chassis with chassistype 'RackMount' to a Rack

### ISSUE THREAD

**Issue by skhan-anjum** [ODIM-Project/ODIM#308]
Steps to Reproduce:

1. Start URP service
2. Add computer system chassis with ChassisType 'RackMount' in odimra
3. Add URP to odimra
4. Create Rack Group
5. Create Rack and do a patch operation on the uri returned in Location in response header as mentioned in 4th step
6. Attach Computer System chassis to rack

Expected Response code: 200
Actual Response:
400 Bad Request
{
    "error": {
        "code": "Base.1.6.1.GeneralError",
        "message": "An error has occurred. See ExtendedInfo for more information.",
        "@Message.ExtendedInfo": [
            {
                "@odata.type": "#Message.v1_0_8.Message",
                "MessageId": "Base.1.6.1.PropertyValueNotInList",
                "Message": "The value [{/redfish/v1/Chassis/<chassis_id>}] for the property Links.Contains is not in the list of acceptable values. Couldn't confirm existence of one or more requested 'Links.Contains' elements or one of them is not a pointer to Chassis asset",
                "MessageArgs": [
                    "[{/redfish/v1/Chassis/<chassis_id>}]",
                    "Links.Contains"
                ],
                "Severity": "Warning",
                "Resolution": "Choose a value from the enumeration list that the implementation can support and resubmit the request if the operation failed."
            }
        ]
    }
}

**Comment by rpieczon** [comment]
Could you attach URP's logs?

**Comment by skhan-anjum** [comment]
Below are the URP logs:
Jan  4 16:18:11.290 [INFO] Starting URP v4cff452-20201229-dirty
Jan  4 16:18:11.336 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:101] POST: /ODIM/v1/Startup -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.basicAuthHandler.handle-fm() and 2 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:98] POST: /EventService/Events -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*eventHandler).handleEvent-fm() and 1 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:106] GET: /ODIM/v1/Managers/{id} -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*getPluginManagerHandler).handle-fm() and 2 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:110] GET: /ODIM/v1/Chassis/{id} -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*getChassisHandler).handle-fm() and 2 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:102] GET: /ODIM/v1/Status -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.pluginStatusController.getPluginStatus-fm() and 1 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:105] GET: /ODIM/v1/Managers -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*getManagersHandler).handle-fm() and 2 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:109] GET: /ODIM/v1/Chassis -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*getChassisCollectionHandler).handle-fm() and 2 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:111] DELETE: /ODIM/v1/Chassis/{id} -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*deleteChassisHandler).handle-fm() and 2 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:112] POST: /ODIM/v1/Chassis -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*postChassisHandler).handle-fm() and 2 more
Jan  4 16:18:11.337 [DEBU] [./home/anjum/go/src/github.com/URP_4jan/ODIM/plugin-unmanaged-racks/rest/module.go:113] PATCH: /ODIM/v1/Chassis/{id} -> github.com/ODIM-Project/ODIM/plugin-unmanaged-racks/rest.(*chassisUpdateHandler).handle-fm() and 2 more
Jan  4 16:18:11.338 [DEBU] Application: running using 1 host(s)
Jan  4 16:18:11.338 [DEBU] Host: addr is URP:45003
Jan  4 16:18:11.338 [DEBU] Host: virtual host is URP:45003
Jan  4 16:18:11.338 [DEBU] Host: register server shutdown on interrupt(CTRL+C/CMD+C)
Jan  4 16:25:58.692 [INFO] 200 568.116µs 192.168.144.1 GET /ODIM/v1/Status
Jan  4 16:25:58.786 [INFO] 200 665.364µs 192.168.144.1 GET /ODIM/v1/Managers
Jan  4 16:25:58.827 [INFO] 200 197.292µs 192.168.144.1 GET /ODIM/v1/Managers/99999999-9999-9999-9999-999999999999
Jan  4 16:26:17.146 [INFO] 201 3.272256ms 192.168.144.1 POST /ODIM/v1/Chassis
Jan  4 16:26:29.135 [INFO] 201 1.240833ms 192.168.144.1 POST /ODIM/v1/Chassis
Jan  4 16:26:49.703 [INFO] 200 661.358µs 192.168.144.1 GET /ODIM/v1/Chassis
Jan  4 16:27:20.870 [ERRO] cannot read validate https://ODIMRA/redfish/v1/Chassis: &{{Base.1.6.1.GeneralError Get https://10.24.1.25:45000/redfish/v1/Chassis: x509: cannot validate certificate for 10.24.1.25 because it doesn't contain any IP SANs []}}
Jan  4 16:27:20.870 [INFO] 400 5.872646ms 192.168.144.1 PATCH /ODIM/v1/Chassis/7299564e-2c9b-55c1-a35e-8cfae21808c2

**Comment by skhan-anjum** [comment]
Also, we are using docker for deployment of odimra which deploys urp also with odimra i.e we are not doing make separately for urp.

**Comment by rpieczon** [comment]
Regarding to following message: 

`Jan 4 16:27:20.870 [ERRO] cannot read validate https://ODIMRA/redfish/v1/Chassis: &{{Base.1.6.1.GeneralError Get https://10.24.1.25:45000/redfish/v1/Chassis: x509: cannot validate certificate for 10.24.1.25 because it doesn't contain any IP SANs []}}`

URP cannot validate certificate of ODIM. URP deployment (described in docker-compose.yml) has to specify value for `PLUGIN_ODIM_URL` which is compatible with ODIM's NB API certificate.

**Comment by rpieczon** [comment]
Fixed.

**Comment by skhan-anjum** [comment]
Verified - Attach computer system chassis to Rack works now
