### ISSUE TITLE
recipe for target 'urp' failed

### ISSUE THREAD

**Issue by jaymainal** [ODIM-Project/ODIM#318]
Hi 

I noticed you release ODIM 20.01 recently.
I tried to install the new ODIM in my environment. 
But I got an issue about 'urp'. Please check the below picture and may know what is the 'urp'

![image](https://user-images.githubusercontent.com/25766337/104699793-38fb7000-574e-11eb-9c6a-e9ee1de012d4.png)

![image](https://user-images.githubusercontent.com/25766337/104700123-a7d8c900-574e-11eb-9b7b-de14ea9f1871.png)

Thanks

**Comment by skhan-anjum** [comment]
Resolved with PR : https://github.com/ODIM-Project/ODIM/pull/370
