### ISSUE TITLE
remove unnecessary `` from README.md

### ISSUE THREAD

**Issue by Bharath-KKB** [ODIM-Project/ODIM#328]
The README.md file at https://github.com/ODIM-Project/ODIM has the following:
++++++++++++++++++++++++++++++++++++++++++++++++++++++
NOTE: To enable Docker service to start on reboot, run the following command:

`$ sudo systemctl enable docker`
++++++++++++++++++++++++++++++++++++++++++++++++++++++

remove the ``.

**Comment by chinmayic** [comment]
Removed.
