### ISSUE TITLE
README.md needs updating

### ISSUE THREAD

**Issue by ehsjoar** [ODIM-Project/ODIM#345]
The current README.md talks about ODIMRA, which is not a known thing in the community. It also mentions GRF without introducing the acronym. Finally, we should introduce what ODIM is before we dive into how to install it. The reason for a high priority here is that there is an upcoming release and we need it fixed before that release.

**Comment by ashraf-vazeer** [comment]
Introduction to ODIMRA is added. 
Acronym for GRF is also added
