### ISSUE TITLE
Build fails following README.md

### ISSUE THREAD

**Issue by ehsjoar** [ODIM-Project/ODIM#354]
We cannot release with this failure. What am I missing?

go: finding github.com/fsnotify/fsnotify v1.4.9
Build for odimra service/lib dependencies svc-aggregation are Successful !!!!
Build for odimra service/lib dependencies svc-api are Successful !!!!
Build for odimra service/lib dependencies svc-events are Successful !!!!
Build for odimra service/lib dependencies svc-fabrics are Successful !!!!
Build for odimra service/lib dependencies svc-managers are Successful !!!!
Build for odimra service/lib dependencies svc-systems are Successful !!!!
go: finding github.com/satori/uuid v1.2.0
Build for odimra service/lib dependencies svc-task are Successful !!!!
Build for odimra service/lib dependencies svc-update are Successful !!!!
Build for odimra service/lib dependencies svc-events are Successful !!!!
Removing intermediate container 6935cf04a99a
 ---> e08169cd5a95
Successfully built e08169cd5a95
Successfully tagged odimra_builddep:tst
cd plugin-unmanaged-racks && make build
make[1]: Entering directory '/home/jonas/ODIM/plugin-unmanaged-racks'
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -ldflags "-X main.version=4a510cc-20210125-dirty" -o ../build/plugin-unmanaged-racks/tmp/urp main.go
/bin/sh: 1: go: not found
Makefile:33: recipe for target 'compile' failed
make[1]: *** [compile] Error 127
make[1]: Leaving directory '/home/jonas/ODIM/plugin-unmanaged-racks'
Makefile:35: recipe for target 'urp' failed
make: *** [urp] Error 2

**Comment by skhan-anjum** [comment]
Resolved with PR : #370
