### ISSUE TITLE
make clean fails in RC0

### ISSUE THREAD

**Issue by ehsjoar** [ODIM-Project/ODIM#355]
Following README.md make clean fails:
We cannot release with these issues

jonas@odim:~/ODIM$ make clean
build/cleanupbuild.sh
WARNING: The https_proxy variable is not set. Defaulting to a blank string.
WARNING: The http_proxy variable is not set. Defaulting to a blank string.
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
Cleanup done
cd plugin-unmanaged-racks && make clean
make[1]: Entering directory '/home/jonas/ODIM/plugin-unmanaged-racks'
rm -r BUILD_DIR
rm: cannot remove 'BUILD_DIR': No such file or directory
Makefile:30: recipe for target 'clean' failed
make[1]: *** [clean] Error 1
make[1]: Leaving directory '/home/jonas/ODIM/plugin-unmanaged-racks'
Makefile:49: recipe for target 'clean' failed
make: *** [clean] Error 2

**Comment by skhan-anjum** [comment]
Resolved with PR : #370
