### ISSUE TITLE
Typo in GRF plugin

### ISSUE THREAD

**Issue by ArturBaryla** [ODIM-Project/ODIM#391]
Bug line:
https://github.com/ODIM-Project/ODIM/blob/31ab2796a0bdf4f0e79c3dbfcf9594eaf9a6c1ac/plugin-redfish/main.go#L144

In redfish schema the resource collection is named `PCIeDevices` and in ODIM code there is `PCIDevices`

**Comment by tamanna-k** [comment]
closing the issue based on PR: https://github.com/ODIM-Project/ODIM/pull/403
