### ISSUE TITLE
Adding BMC  with system-id BMC  not displaying proper managers URI 

### ISSUE THREAD

**Issue by jeevan-kamkar** [ODIM-Project/ODIM#398]
Adding BMC with systemid= BMC should display system URI of added BMC as `/redfish/v1/Managers/UUID:BMC` instead it's giving system URI as `/redfish/v1/Managers/BMC`

**Comment by shivacharanms** [comment]
Unable to reproduce in our systems, please provide access to your environment.

**Comment by bharath-b-hpe** [comment]
Issue is not reproducible and is working as expected, hence closing this issue.
