### ISSUE TITLE
Route for the individual processor is missing in the GRF plugin 

### ISSUE THREAD

**Issue by jeevan-kamkar** [ODIM-Project/ODIM#399]
Route for the individual processor `/redfish/v1/Systems/{id}/Processors/{rid` is missing in the GRF plugin

**Comment by tamanna-k** [comment]
issue is resolved as part of PR: https://github.com/ODIM-Project/ODIM/pull/435

**Comment by jeevan-kamkar** [comment]
Closing the issue based on the #435 pr
