### ISSUE TITLE
ODIM should send POST not PATCH at  /redfish/v1/Systems/1/Actions/ComputerSystem.SetDefaultBootOrder

### ISSUE THREAD

**Issue by ArturBaryla** [ODIM-Project/ODIM#407]
When I sending `POST` at `"/redfish/v1/Systems/{id}/Actions/ComputerSystem.SetDefaultBootOrder"`
ODIM is sending `PATCH` to the BMC service.

**Comment by ArturBaryla** [comment]
Pull request: https://github.com/ODIM-Project/ODIM/pull/477

**Comment by bharath-b-hpe** [comment]
Hello @ArturBaryla 

Please let me know if this issue can be closed.

**Comment by ehaligow** [comment]
I think the issue can be closed - BMC is receiving POST request from ODIM.

**Comment by bharath-b-hpe** [comment]
Thanks @ehaligow for confirming, closing the issue.
