### ISSUE TITLE
GET ON /redfish/v1/Registries/ is giving incorrect link under Location URI

### ISSUE THREAD

**Issue by nimmalagautam** [ODIM-Project/ODIM#507]
GET ON https://<odimip>:port/redfish/v1/Registries/BiosAttributeRegistryU32.v1_2_36

 

we are getting  the registries in a small letter instead of capital R in registries 

            "Uri": "/redfish/v1/registries/BiosAttributeRegistryU32.v1_2_36.json"

**Comment by jeevan-kamkar** [comment]
closing the issue base merge of #509
