### ISSUE TITLE
Replace go-micro with gRPC framework

### ISSUE THREAD

**Issue by a-ajith** [ODIM-Project/ODIM#523]
Replace the go-micro framework used for service discovery and inter-service communication with the standard gRPC framework with etcd for service discovery functionality.

- [x] Add reusable code to the lib-utilities which supports gRPC implementation
- [x] Add etcd to the Kubernetes deployment
- [x] Add etcd to the Docker deployment
- [x] Create svc-managers gRPC server and client
- [x] Create svc-fabric gRPC server and client
- [x] Create svc-events gRPC server and client
- [x] Create svc-system gRPC server and client
- [x] Create svc-task gRPC server and client
- [x] Create svc-account-session gRPC server and client
- [x] Create svc-aggregation gRPC server and client
- [x] Create svc-update gRPC server and client
- [ ] Create svc-telemetry gRPC server and client
- [ ] Remove consul from both Docker and Kubernetes deployment
- [x] Documenting steps for generating proto files

**Comment by skhan-anjum** [comment]
Closing this issue as new issue https://jira.lfnetworking.org/browse/ODIM-14 is created
