### ISSUE TITLE
[Enhancement] Add missing properties for UpdateService

### ISSUE THREAD

**Issue by ehaligow** [ODIM-Project/ODIM#557]
According to Open Process Automation Forum and their standard for Redfish profile (supporting document: https://www.opengroup.org/sites/default/files/pdf/O-PAS-OSM-002-v2_0_0.json) following properties are mandatory, but missing in ODIM:
HttpPushUriOptions, HttpPushUriOptionsBus, HttpPushUriTargets, HttpPushUriTargetsBusy, MaxImageSizeBytes, MultipartHttpPushUri.

**Comment by bharath-b-hpe** [comment]
Hello @ehaligow 

Thanks for reporting the observation.

HttpPushUriOptions, HttpPushUriOptionsBus, HttpPushUriTargets, HttpPushUriTargetsBusy, MaxImageSizeBytes, MultipartHttpPushUri properties are not mandatory but recommended to support, according to schema(https://redfish.dmtf.org/schemas/v1/UpdateService.v1_8_1.json) and https://www.opengroup.org/sites/default/files/pdf/O-PAS-OSM-002-v2_0_0.json as well.

Changes will be made in the ODIMRA to support these properties, but changes in the plugins will be made only if the devices it's managing support these properties.

**Comment by shivacharanms** [comment]
Hi @ehaligow 

To add the httpPushUri feature support into UpdateService please raise a request in the ODIM TSC(Technical Steering Committee) as this is a recommended option and not a mandatory one, link to the same as below.

https://wiki.odim.io/display/HOME/Technical+Steering+Committee

**Comment by bharath-b-hpe** [comment]
Request added as new feature proposal in TSC list at https://wiki.odim.io/pages/viewpage.action?pageId=327873. Hence closing this issue.
